// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/aether/sync.proto

package aether

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthChallenge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthChallenge) Reset() {
	*x = AuthChallenge{}
	mi := &file_proto_aether_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthChallenge) ProtoMessage() {}

func (x *AuthChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aether_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthChallenge.ProtoReflect.Descriptor instead.
func (*AuthChallenge) Descriptor() ([]byte, []int) {
	return file_proto_aether_sync_proto_rawDescGZIP(), []int{0}
}

func (x *AuthChallenge) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *AuthChallenge) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      []byte                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // PeerID bytes
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`               // Ed25519 signature of the nonce
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`              // Client's timestamp for replay protection
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_proto_aether_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aether_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_proto_aether_sync_proto_rawDescGZIP(), []int{1}
}

func (x *AuthResponse) GetDeviceId() []byte {
	if x != nil {
		return x.DeviceId
	}
	return nil
}

func (x *AuthResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AuthResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type AuthResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	SessionToken  string                 `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"` // Optional: for subsequent validation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResult) Reset() {
	*x = AuthResult{}
	mi := &file_proto_aether_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResult) ProtoMessage() {}

func (x *AuthResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aether_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResult.ProtoReflect.Descriptor instead.
func (*AuthResult) Descriptor() ([]byte, []int) {
	return file_proto_aether_sync_proto_rawDescGZIP(), []int{2}
}

func (x *AuthResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AuthResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *AuthResult) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AfterSeq      int64                  `protobuf:"varint,1,opt,name=after_seq,json=afterSeq,proto3" json:"after_seq,omitempty"` // Request messages with global_seq > after_seq
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                       // Max messages to return
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_proto_aether_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aether_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_proto_aether_sync_proto_rawDescGZIP(), []int{3}
}

func (x *FetchRequest) GetAfterSeq() int64 {
	if x != nil {
		return x.AfterSeq
	}
	return 0
}

func (x *FetchRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SyncMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConversationId  string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	SenderId        string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Content         []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"` // Encrypted payload
	GlobalSeq       int64                  `protobuf:"varint,5,opt,name=global_seq,json=globalSeq,proto3" json:"global_seq,omitempty"`
	SenderSignature []byte                 `protobuf:"bytes,6,opt,name=sender_signature,json=senderSignature,proto3" json:"sender_signature,omitempty"`
	SentAt          int64                  `protobuf:"varint,7,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SyncMessage) Reset() {
	*x = SyncMessage{}
	mi := &file_proto_aether_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMessage) ProtoMessage() {}

func (x *SyncMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aether_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMessage.ProtoReflect.Descriptor instead.
func (*SyncMessage) Descriptor() ([]byte, []int) {
	return file_proto_aether_sync_proto_rawDescGZIP(), []int{4}
}

func (x *SyncMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SyncMessage) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *SyncMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *SyncMessage) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *SyncMessage) GetGlobalSeq() int64 {
	if x != nil {
		return x.GlobalSeq
	}
	return 0
}

func (x *SyncMessage) GetSenderSignature() []byte {
	if x != nil {
		return x.SenderSignature
	}
	return nil
}

func (x *SyncMessage) GetSentAt() int64 {
	if x != nil {
		return x.SentAt
	}
	return 0
}

type FetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*SyncMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	MaxSeq        int64                  `protobuf:"varint,2,opt,name=max_seq,json=maxSeq,proto3" json:"max_seq,omitempty"` // Highest global_seq in this batch
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_proto_aether_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aether_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_proto_aether_sync_proto_rawDescGZIP(), []int{5}
}

func (x *FetchResponse) GetMessages() []*SyncMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *FetchResponse) GetMaxSeq() int64 {
	if x != nil {
		return x.MaxSeq
	}
	return 0
}

func (x *FetchResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type AckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AckedSeq      int64                  `protobuf:"varint,1,opt,name=acked_seq,json=ackedSeq,proto3" json:"acked_seq,omitempty"` // Highest sequence successfully saved by client
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_proto_aether_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aether_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_proto_aether_sync_proto_rawDescGZIP(), []int{6}
}

func (x *AckRequest) GetAckedSeq() int64 {
	if x != nil {
		return x.AckedSeq
	}
	return 0
}

type AckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_proto_aether_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aether_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_proto_aether_sync_proto_rawDescGZIP(), []int{7}
}

func (x *AckResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type PushEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*PushEnvelope_NewMessage
	//	*PushEnvelope_Delivery
	//	*PushEnvelope_Read
	Type          isPushEnvelope_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushEnvelope) Reset() {
	*x = PushEnvelope{}
	mi := &file_proto_aether_sync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushEnvelope) ProtoMessage() {}

func (x *PushEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aether_sync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushEnvelope.ProtoReflect.Descriptor instead.
func (*PushEnvelope) Descriptor() ([]byte, []int) {
	return file_proto_aether_sync_proto_rawDescGZIP(), []int{8}
}

func (x *PushEnvelope) GetType() isPushEnvelope_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *PushEnvelope) GetNewMessage() *SyncMessage {
	if x != nil {
		if x, ok := x.Type.(*PushEnvelope_NewMessage); ok {
			return x.NewMessage
		}
	}
	return nil
}

func (x *PushEnvelope) GetDelivery() *DeliveryReceipt {
	if x != nil {
		if x, ok := x.Type.(*PushEnvelope_Delivery); ok {
			return x.Delivery
		}
	}
	return nil
}

func (x *PushEnvelope) GetRead() *ReadReceipt {
	if x != nil {
		if x, ok := x.Type.(*PushEnvelope_Read); ok {
			return x.Read
		}
	}
	return nil
}

type isPushEnvelope_Type interface {
	isPushEnvelope_Type()
}

type PushEnvelope_NewMessage struct {
	NewMessage *SyncMessage `protobuf:"bytes,1,opt,name=new_message,json=newMessage,proto3,oneof"`
}

type PushEnvelope_Delivery struct {
	Delivery *DeliveryReceipt `protobuf:"bytes,2,opt,name=delivery,proto3,oneof"`
}

type PushEnvelope_Read struct {
	Read *ReadReceipt `protobuf:"bytes,3,opt,name=read,proto3,oneof"`
}

func (*PushEnvelope_NewMessage) isPushEnvelope_Type() {}

func (*PushEnvelope_Delivery) isPushEnvelope_Type() {}

func (*PushEnvelope_Read) isPushEnvelope_Type() {}

type DeliveryReceipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeliveredAt   int64                  `protobuf:"varint,3,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryReceipt) Reset() {
	*x = DeliveryReceipt{}
	mi := &file_proto_aether_sync_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryReceipt) ProtoMessage() {}

func (x *DeliveryReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aether_sync_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryReceipt.ProtoReflect.Descriptor instead.
func (*DeliveryReceipt) Descriptor() ([]byte, []int) {
	return file_proto_aether_sync_proto_rawDescGZIP(), []int{9}
}

func (x *DeliveryReceipt) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *DeliveryReceipt) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeliveryReceipt) GetDeliveredAt() int64 {
	if x != nil {
		return x.DeliveredAt
	}
	return 0
}

type ReadReceipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ReadAt        int64                  `protobuf:"varint,3,opt,name=read_at,json=readAt,proto3" json:"read_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadReceipt) Reset() {
	*x = ReadReceipt{}
	mi := &file_proto_aether_sync_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadReceipt) ProtoMessage() {}

func (x *ReadReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aether_sync_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadReceipt.ProtoReflect.Descriptor instead.
func (*ReadReceipt) Descriptor() ([]byte, []int) {
	return file_proto_aether_sync_proto_rawDescGZIP(), []int{10}
}

func (x *ReadReceipt) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ReadReceipt) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ReadReceipt) GetReadAt() int64 {
	if x != nil {
		return x.ReadAt
	}
	return 0
}

var File_proto_aether_sync_proto protoreflect.FileDescriptor

const file_proto_aether_sync_proto_rawDesc = "" +
	"\n" +
	"\x17proto/aether/sync.proto\x12\vaether.sync\"D\n" +
	"\rAuthChallenge\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\"g\n" +
	"\fAuthResponse\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\fR\bdeviceId\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"f\n" +
	"\n" +
	"AuthResult\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12#\n" +
	"\rsession_token\x18\x03 \x01(\tR\fsessionToken\"A\n" +
	"\fFetchRequest\x12\x1b\n" +
	"\tafter_seq\x18\x01 \x01(\x03R\bafterSeq\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"\xe0\x01\n" +
	"\vSyncMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\x12\x1d\n" +
	"\n" +
	"global_seq\x18\x05 \x01(\x03R\tglobalSeq\x12)\n" +
	"\x10sender_signature\x18\x06 \x01(\fR\x0fsenderSignature\x12\x17\n" +
	"\asent_at\x18\a \x01(\x03R\x06sentAt\"y\n" +
	"\rFetchResponse\x124\n" +
	"\bmessages\x18\x01 \x03(\v2\x18.aether.sync.SyncMessageR\bmessages\x12\x17\n" +
	"\amax_seq\x18\x02 \x01(\x03R\x06maxSeq\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\")\n" +
	"\n" +
	"AckRequest\x12\x1b\n" +
	"\tacked_seq\x18\x01 \x01(\x03R\backedSeq\"\x1d\n" +
	"\vAckResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\xbf\x01\n" +
	"\fPushEnvelope\x12;\n" +
	"\vnew_message\x18\x01 \x01(\v2\x18.aether.sync.SyncMessageH\x00R\n" +
	"newMessage\x12:\n" +
	"\bdelivery\x18\x02 \x01(\v2\x1c.aether.sync.DeliveryReceiptH\x00R\bdelivery\x12.\n" +
	"\x04read\x18\x03 \x01(\v2\x18.aether.sync.ReadReceiptH\x00R\x04readB\x06\n" +
	"\x04type\"p\n" +
	"\x0fDeliveryReceipt\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12!\n" +
	"\fdelivered_at\x18\x03 \x01(\x03R\vdeliveredAt\"b\n" +
	"\vReadReceipt\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x17\n" +
	"\aread_at\x18\x03 \x01(\x03R\x06readAtB%Z#github.com/user/aether/proto/aetherb\x06proto3"

var (
	file_proto_aether_sync_proto_rawDescOnce sync.Once
	file_proto_aether_sync_proto_rawDescData []byte
)

func file_proto_aether_sync_proto_rawDescGZIP() []byte {
	file_proto_aether_sync_proto_rawDescOnce.Do(func() {
		file_proto_aether_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_aether_sync_proto_rawDesc), len(file_proto_aether_sync_proto_rawDesc)))
	})
	return file_proto_aether_sync_proto_rawDescData
}

var file_proto_aether_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_aether_sync_proto_goTypes = []any{
	(*AuthChallenge)(nil),   // 0: aether.sync.AuthChallenge
	(*AuthResponse)(nil),    // 1: aether.sync.AuthResponse
	(*AuthResult)(nil),      // 2: aether.sync.AuthResult
	(*FetchRequest)(nil),    // 3: aether.sync.FetchRequest
	(*SyncMessage)(nil),     // 4: aether.sync.SyncMessage
	(*FetchResponse)(nil),   // 5: aether.sync.FetchResponse
	(*AckRequest)(nil),      // 6: aether.sync.AckRequest
	(*AckResponse)(nil),     // 7: aether.sync.AckResponse
	(*PushEnvelope)(nil),    // 8: aether.sync.PushEnvelope
	(*DeliveryReceipt)(nil), // 9: aether.sync.DeliveryReceipt
	(*ReadReceipt)(nil),     // 10: aether.sync.ReadReceipt
}
var file_proto_aether_sync_proto_depIdxs = []int32{
	4,  // 0: aether.sync.FetchResponse.messages:type_name -> aether.sync.SyncMessage
	4,  // 1: aether.sync.PushEnvelope.new_message:type_name -> aether.sync.SyncMessage
	9,  // 2: aether.sync.PushEnvelope.delivery:type_name -> aether.sync.DeliveryReceipt
	10, // 3: aether.sync.PushEnvelope.read:type_name -> aether.sync.ReadReceipt
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_aether_sync_proto_init() }
func file_proto_aether_sync_proto_init() {
	if File_proto_aether_sync_proto != nil {
		return
	}
	file_proto_aether_sync_proto_msgTypes[8].OneofWrappers = []any{
		(*PushEnvelope_NewMessage)(nil),
		(*PushEnvelope_Delivery)(nil),
		(*PushEnvelope_Read)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_aether_sync_proto_rawDesc), len(file_proto_aether_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_aether_sync_proto_goTypes,
		DependencyIndexes: file_proto_aether_sync_proto_depIdxs,
		MessageInfos:      file_proto_aether_sync_proto_msgTypes,
	}.Build()
	File_proto_aether_sync_proto = out.File
	file_proto_aether_sync_proto_goTypes = nil
	file_proto_aether_sync_proto_depIdxs = nil
}
